# This file configures the build and deployment settings for Netlify.

# 1. Build Settings
# Specifies the command to run to build the site and the directory
# where the finished static files are located.
[build]
  command = "npm run build"
  publish = "dist/client"

# 2. Netlify Functions Configuration
# Tells Netlify where to find and how to build the serverless functions.
[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild"

# 3. Redirect Rules
# The first rule is for your API. It rewrites any request to /api/...
# to the 'api' serverless function we just created.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# The second rule is the catch-all for the Single-Page Application.
# It ensures that any direct navigation to a frontend route works correctly.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 